export const ADMIN_TEXT = {
  COMMON: {
    SEARCH: "검색",
    LOADING: "데이터를 불러오는 중입니다...",
    NO_RESULT: "검색 결과가 없습니다.",
    FILTER: {
      ALL: "전체 상태",
      ACTIVE: "활동",
      BANNED: "정지",
      POSTING: "게시 중", // For posts
      DELETED: "삭제됨", // For posts
      TRAINER: "트레이너",
      MEMBER: "회원",
      ALL_ROLES: "전체 역할",
    },
  },
  USER: {
    TITLE_TOTAL: "총 사용자",
    TITLE_BANNED: "정지된 사용자",
    SEARCH_PLACEHOLDER: "사용자의 ID 혹은 닉네임을 검색하세요",
    TABLE: {
      USER: "사용자",
      EMAIL: "이메일",
      JOIN_DATE: "가입일",
      STATUS: "상태",
      ACTIVITY: "활동",
      MANAGE: "관리",
      ACTIVITY_FORMAT: "게시글 %POSTS% · 댓글 %COMMENTS%",
    },
    BTN_BAN: "정지",
    BTN_UNBAN: "해제",
    MSG_BAN_SUCCESS: "사용자를 정지했습니다.",
    MSG_UNBAN_SUCCESS: "사용자 정지를 해제했습니다.",
    MSG_BAN_FAILED: "사용자 정지에 실패했습니다.",
    MSG_UNBAN_FAILED: "사용자 정지 해제에 실패했습니다.",
  },
  POST: {
    SEARCH_PLACEHOLDER: "포스트 혹은 댓글 내용을 검색하세요",
    BTN_DELETE_POST: "게시글 삭제",
    BTN_RESTORE_POST: "게시글 복구",
    BTN_DELETE_COMMENT: "삭제",
    BTN_RESTORE_COMMENT: "복구",
    LABEL_COMMENT: "댓글",
    LABEL_DELETED_COMMENT: "삭제된 댓글",
    BTN_COMMENT_FOLD: "댓글 접기",
    BTN_COMMENT_MORE: "댓글 더보기",
    MSG_NO_MORE_POSTS: "더 이상 표시할 게시글이 없습니다.",
    REASONS: [
      { label: "부적절한 내용", value: "INAPPROPRIATE" },
      { label: "스팸/광고", value: "SPAM" },
      { label: "욕설 및 어뷰징", value: "HARASSMENT" },
      { label: "운영정책 위반", value: "POLICY_VIOLATION" },
      { label: "기타", value: "OTHER" },
    ],
    MODAL: {
      TITLE: "정말로 %TYPE%을 삭제하시겠어요?", // Placeholder for formatted string
      SELECT_REASON: "이유를 선택해주세요",
      BTN_CANCEL: "취소",
      BTN_DELETE: "삭제",
    },
    BOARD_TYPE: {
      FREE: "자유게시판",
      QUESTION: "질문게시판",
    },
    BTN_ESCROW: "에스크로 관리",
    BTN_SETTLE: "정산",
    MSG_BAN_REASON: "관리자 직권 정지",
    MSG_UNBAN_REASON: "관리자 정지 해제",
    MSG_DELETE_REASON: "관리자 직권 삭제",
  },
  ACCOUNTS: {
    TITLE: "관리자 계정 관리",
    BTN_ADD: "관리자 추가",
    TABLE: {
      ID: "ID",
      NICKNAME: "닉네임",
      ROLE: "역할",
      CREATED_AT: "생성일",
      LAST_LOGIN: "마지막 로그인",
      MANAGE: "관리",
      EMPTY: "등록된 관리자 계정이 없습니다.",
    },
    MSG_CREATE_SUCCESS: "관리자 계정이 생성되었습니다.",
    MSG_CREATE_FAILED: "관리자 계정 생성에 실패했습니다.",
    CONFIRM_RESET: "해당 관리자의 비밀번호를 초기화하시겠습니까?",
    MSG_RESET_SUCCESS: "비밀번호가 초기화되었습니다.",
    MSG_RESET_FAILED: "비밀번호 초기화에 실패했습니다.",
    MODAL: {
      TITLE: "새 관리자 계정 추가",
      LABEL_ID: "로그인 ID",
      PLACEHOLDER_ID: "ID를 입력하세요",
      LABEL_NICKNAME: "닉네임",
      PLACEHOLDER_NICKNAME: "표시될 이름을 입력하세요",
      BTN_CANCEL: "취소",
      BTN_CREATE: "생성하기",
    },
  },
  SETTINGS: {
    TITLE: "시스템 설정",
    SUBTITLE: "관리자 보안 및 시스템 복구 설정을 관리합니다.",
    PASSWORD: {
      TITLE: "비밀번호 변경",
      LABEL_CURRENT: "현재 비밀번호",
      LABEL_NEW: "새 비밀번호",
      LABEL_CONFIRM: "새 비밀번호 확인",
      BTN_SUBMIT: "비밀번호 변경 실행",
      MSG_SUCCESS: "비밀번호가 성공적으로 변경되었습니다.",
      MSG_FAILED: "비밀번호 변경에 실패했습니다. 현재 비밀번호를 확인해주세요.",
      MSG_MISMATCH: "새 비밀번호가 일치하지 않습니다.",
      MSG_REQUIRED: "비밀번호를 입력해주세요.",
    },
    RECOVERY: {
      TITLE: "시스템 복구 및 재설정",
      DANGER_ZONE: "위험구역 (Danger Zone)",
      DANGER_DESC:
        "시스템 시드 재설정(Reseed)은 모든 관리자 권한 및 시스템 보안 설정을 초기화하고 재구축합니다. 반드시 매뉴얼을 숙지한 후 진행하십시오.",
      BTN_RESEED: "시스템 재설정 시작",
      CONFIRM_RESEED:
        "시스템 시드 재설정(Reseed)을 진행하시겠습니까? 이 작업은 되돌릴 수 없으며 시스템 보안에 중대한 영향을 미칩니다.",
      MSG_SUCCESS: "시스템 재설정이 완료되었습니다.",
      MSG_FAILED: "시스템 재설정에 실패했습니다.",
    },
  },
  WEB3: {
    TITLE: "Web3 트랜잭션 관리",
    CONFIRM_TX: "트랜잭션 #%ID%를 강제로 '성공' 처리하시겠습니까?",
    MSG_CONFIRM_SUCCESS: "성공적으로 처리되었습니다.",
    MSG_CONFIRM_FAILED: "처리에 실패했습니다. ID를 확인해주세요.",
    MANUAL: {
      TITLE: "수동 트랜잭션 확정",
      DESC: "DB ID를 직접 입력하여 트랜잭션 상태를 강제로 'SUCCESS'로 변경합니다.",
    },
    MONITORING: {
      TITLE: "지갑 활동 모니터링 (Recent)",
      LIVE: "LIVE MONITORING",
      FETCHING: "FETCHING...",
      EMPTY: "최근 트랜잭션 기록이 없습니다.",
      DETAIL: "상세보기 ↗",
    },
    TREASURY: {
      TITLE: "금고 키(Treasury Key) 관리",
      SUBTITLE: "시스템 자산 보호를 위한 멀티시그 및 금고 키를 관리합니다.",
      BTN_ADD: "새 금고 키 생성 (Provision)",
      CONFIRM_DISABLE: "금고 키(%ALIAS%)를 비활성화하시겠습니까?",
      CONFIRM_ARCHIVE: "금고 키(%ALIAS%)를 보관(Archive) 처리하시겠습니까?",
      MSG_DISABLE_SUCCESS: "비활성화되었습니다.",
      MSG_ARCHIVE_SUCCESS: "보관 처리되었습니다.",
      MSG_FAILED: "처리에 실패했습니다.",
      EMPTY: "관리 중인 키가 없습니다.",
    },
    MODAL: {
      TITLE: "새 금고 키(Treasury Key) 생성",
      LABEL_KEY: "프라이빗 키 (rawPrivateKey)",
      PLACEHOLDER_KEY: "Private Key를 입력하세요",
      LABEL_ROLE: "역할 (Role)",
      LABEL_ADDRESS: "예상 지갑 주소 (expectedAddress)",
      BTN_CANCEL: "취소",
      BTN_CREATE: "생성하기",
      MSG_SUCCESS: "금고 키가 성공적으로 생성되었습니다.",
      MSG_FAILED: "키 생성에 실패했습니다. 입력값을 확인해주세요.",
    },
  },
  COLORS: {
    AVATARS: [
      "#FFD700",
      "#FFA500",
      "#FF4500",
      "#32CD32",
      "#1E90FF",
      "#BA55D3",
      "#808080",
    ],
    MAIN: "#FF4500",
  },
};
