export const RESERVATION_STATUS = {
  HOLDING: "HOLDING",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  USER_CANCELLED: "USER_CANCELLED",
  REJECTED: "REJECTED",
  TIMEOUT_CANCELLED: "TIMEOUT_CANCELLED",
  SETTLED: "SETTLED",
  AUTO_SETTLED: "AUTO_SETTLED",
  HOLD_EXPIRED: "HOLD_EXPIRED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  DEADLINE_REFUNDED: "DEADLINE_REFUNDED",
  MANUAL_SYNC_REQUIRED: "MANUAL_SYNC_REQUIRED",
  PURCHASE_PREPARING: "PURCHASE_PREPARING",
  PURCHASE_PENDING: "PURCHASE_PENDING",
  CANCEL_PENDING: "CANCEL_PENDING",
  REJECT_PENDING: "REJECT_PENDING",
  CONFIRM_PENDING: "CONFIRM_PENDING",
  ADMIN_REFUND_PENDING: "ADMIN_REFUND_PENDING",
  ADMIN_SETTLE_PENDING: "ADMIN_SETTLE_PENDING",
  DEADLINE_REFUND_PENDING: "DEADLINE_REFUND_PENDING",
  DEADLINE_REFUND_AVAILABLE: "DEADLINE_REFUND_AVAILABLE",
  DEADLINE_RECOVERY_REQUIRED: "DEADLINE_RECOVERY_REQUIRED",
  DEADLINE_SYNC_REQUIRED: "DEADLINE_SYNC_REQUIRED",
} as const;

export type ReservationStatus =
  (typeof RESERVATION_STATUS)[keyof typeof RESERVATION_STATUS];

export const RESERVATION_STATUS_LABEL: Record<ReservationStatus, string> = {
  [RESERVATION_STATUS.HOLDING]: "결제 준비",
  [RESERVATION_STATUS.PENDING]: "승인 대기",
  [RESERVATION_STATUS.APPROVED]: "예약 확정",
  [RESERVATION_STATUS.USER_CANCELLED]: "예약 취소",
  [RESERVATION_STATUS.REJECTED]: "예약 거절",
  [RESERVATION_STATUS.TIMEOUT_CANCELLED]: "자동 취소",
  [RESERVATION_STATUS.SETTLED]: "수업 완료",
  [RESERVATION_STATUS.AUTO_SETTLED]: "자동 정산",
  [RESERVATION_STATUS.HOLD_EXPIRED]: "예약 만료",
  [RESERVATION_STATUS.PAYMENT_FAILED]: "결제 실패",
  [RESERVATION_STATUS.DEADLINE_REFUNDED]: "환불 완료",
  [RESERVATION_STATUS.MANUAL_SYNC_REQUIRED]: "확인 필요",
  [RESERVATION_STATUS.PURCHASE_PREPARING]: "결제 준비",
  [RESERVATION_STATUS.PURCHASE_PENDING]: "결제 진행 중",
  [RESERVATION_STATUS.CANCEL_PENDING]: "취소 진행 중",
  [RESERVATION_STATUS.REJECT_PENDING]: "거절 진행 중",
  [RESERVATION_STATUS.CONFIRM_PENDING]: "완료 확인 중",
  [RESERVATION_STATUS.ADMIN_REFUND_PENDING]: "환불 처리 중",
  [RESERVATION_STATUS.ADMIN_SETTLE_PENDING]: "정산 처리 중",
  [RESERVATION_STATUS.DEADLINE_REFUND_PENDING]: "환불 진행 중",
  [RESERVATION_STATUS.DEADLINE_REFUND_AVAILABLE]: "환불 가능",
  [RESERVATION_STATUS.DEADLINE_RECOVERY_REQUIRED]: "복구 필요",
  [RESERVATION_STATUS.DEADLINE_SYNC_REQUIRED]: "동기화 필요",
};

export const UPCOMING_RESERVATION_STATUSES: ReservationStatus[] = [
  RESERVATION_STATUS.HOLDING,
  RESERVATION_STATUS.PURCHASE_PREPARING,
  RESERVATION_STATUS.PURCHASE_PENDING,
  RESERVATION_STATUS.PENDING,
  RESERVATION_STATUS.APPROVED,
  RESERVATION_STATUS.CANCEL_PENDING,
  RESERVATION_STATUS.REJECT_PENDING,
  RESERVATION_STATUS.CONFIRM_PENDING,
  RESERVATION_STATUS.ADMIN_REFUND_PENDING,
  RESERVATION_STATUS.ADMIN_SETTLE_PENDING,
  RESERVATION_STATUS.DEADLINE_REFUND_PENDING,
  RESERVATION_STATUS.DEADLINE_REFUND_AVAILABLE,
  RESERVATION_STATUS.DEADLINE_RECOVERY_REQUIRED,
  RESERVATION_STATUS.DEADLINE_SYNC_REQUIRED,
  RESERVATION_STATUS.MANUAL_SYNC_REQUIRED,
];

export const PAST_RESERVATION_STATUSES: ReservationStatus[] = [
  RESERVATION_STATUS.USER_CANCELLED,
  RESERVATION_STATUS.REJECTED,
  RESERVATION_STATUS.TIMEOUT_CANCELLED,
  RESERVATION_STATUS.SETTLED,
  RESERVATION_STATUS.AUTO_SETTLED,
  RESERVATION_STATUS.HOLD_EXPIRED,
  RESERVATION_STATUS.PAYMENT_FAILED,
  RESERVATION_STATUS.DEADLINE_REFUNDED,
];

export const getReservationStatusLabel = (status: ReservationStatus) =>
  RESERVATION_STATUS_LABEL[status] ?? status;

export const isReservationPast = (status: ReservationStatus) =>
  PAST_RESERVATION_STATUSES.includes(status);

export const isReservationCancellable = (status: ReservationStatus) =>
  status === RESERVATION_STATUS.PENDING;

export const isReservationCompletable = (status: ReservationStatus) =>
  status === RESERVATION_STATUS.APPROVED;
