import type { ActionType } from "@types";

export const VERIFY_WALLET_TEXT = {
  recoveryBlockedModal: {
    title: "블록체인 확인 지연",
    desc: "이미 전송된 트랜잭션의 결과 확인이 지연되고 있습니다. 중복 실행을 막기 위해 잠시 후 다시 확인해 주세요.",
  },
  invalidAccess: "유효하지 않은 접근입니다.",
  invalidRecovery: "복구된 실행 정보가 유효하지 않습니다.",
  pinFailureModal: {
    title: "인증 실패",
    desc: "잘못된 PIN 번호입니다. 다시 시도해주세요.",
  },
  loading: "블록체인 트랜잭션을 안전하게 처리하고 있습니다...",
  noWallet: {
    title: "지갑을 찾을 수 없어요",
    description: "토큰 보상을 받기 위해 지갑이 필요해요.",
    buttonLabel: "지갑 등록하기",
  },
  pin: {
    title: "PIN 번호 인증",
    descriptionByActionType: {
      QNA_QUESTION_CREATE: "질문 보상 예치를 위해",
      QNA_QUESTION_UPDATE: "질문 수정을 위해",
      QNA_QUESTION_DELETE: "질문 삭제 및 보상 반환을 위해",
      QNA_ANSWER_CREATE: "답변 등록을 위해",
      QNA_ANSWER_UPDATE: "답변 수정을 위해",
      QNA_ANSWER_DELETE: "답변 삭제를 위해",
      QNA_ANSWER_ACCEPT: "답변 채택 및 보상 지급을 위해",
      MARKETPLACE_CLASS_PURCHASE: "클래스 예약 결제를 위해",
      MARKETPLACE_RESERVATION_CANCEL: "예약 취소 및 환불을 위해",
      MARKETPLACE_RESERVATION_COMPLETE: "예약 완료 처리를 위해",
      MARKETPLACE_DEADLINE_REFUND: "예약 환불 처리를 위해",
      MARKETPLACE_TRAINER_REJECT: "예약 거절 및 환불을 위해",
      MARKETPLACE_SETTLEMENT: "정산 처리를 위해",
      WALLET_ESCROW_APPROVE: "지갑 등록 및 토큰 사용 승인을 위해",
    } satisfies Record<ActionType, string>,
    defaultDescription: "트랜잭션 실행 및 블록체인 서명을 위해",
    instruction: "PIN 번호를 입력해주세요",
  },
  success: {
    titleByActionType: {
      QNA_QUESTION_CREATE: "질문 등록 요청이 완료되었어요",
      QNA_QUESTION_UPDATE: "질문 수정 요청이 완료되었어요",
      QNA_QUESTION_DELETE: "질문 삭제 요청이 완료되었어요",
      QNA_ANSWER_CREATE: "답변 등록 요청이 완료되었어요",
      QNA_ANSWER_UPDATE: "답변 수정 요청이 완료되었어요",
      QNA_ANSWER_DELETE: "답변 삭제 요청이 완료되었어요",
      QNA_ANSWER_ACCEPT: "답변 채택 요청이 완료되었어요",
      MARKETPLACE_CLASS_PURCHASE: "클래스 예약 요청이 완료되었어요",
      MARKETPLACE_RESERVATION_CANCEL: "예약 취소 요청이 완료되었어요",
      MARKETPLACE_RESERVATION_COMPLETE: "예약 완료 요청이 완료되었어요",
      MARKETPLACE_DEADLINE_REFUND: "예약 환불 요청이 완료되었어요",
      MARKETPLACE_TRAINER_REJECT: "예약 거절 요청이 완료되었어요",
      MARKETPLACE_SETTLEMENT: "정산 요청이 완료되었어요",
      WALLET_ESCROW_APPROVE: "지갑 등록 요청이 완료되었어요",
    } satisfies Record<ActionType, string>,
    defaultTitle: "트랜잭션 수행 요청이 완료되었어요",
    description: [
      "블록체인 네트워크에서 처리가 완료되면",
      "커뮤니티에서 게시글을 확인하실 수 있습니다.",
    ],
    buttonLabel: "확인",
  },
  modal: {
    retryButtonLabel: "다시 시도하기",
    postErrorTitle: "요청 실패",
    walletErrorTitle: "서명 실패",
  },
} as const;
